# Generated by Django 4.2.7 on 2023-11-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='user_images/default.png', upload_to='user_images', verbose_name='Фото профілю'),
        ),
    ]
